services:
  postgres:
    image: postgres:17-alpine
    container_name: lds-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'YourStrong!Passw0rd'
      POSTGRES_DB: LightningSpace
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  postgres-data:
